org: olbirjukov
app: door-guard-api
service:
  name: door-guard-api

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

include:
    - src/**/*  

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations  

provider:
  name: aws
  runtime: nodejs10.x
  environment:
    DYNAMODB_TABLE_DEVICE_PHONE: ${self:service}-${opt:stage, self:provider.stage}-device-phone
    DYNAMODB_TABLE_DEVICE_REQUEST_TOKEN: ${self:service}-${opt:stage, self:provider.stage}-device-request-token
    DYNAMODB_LOCAL_ENDPOINT: http://localhost:8000
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE_DEVICE_PHONE}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE_DEVICE_REQUEST_TOKEN}"
    - Effect: Allow
      Action:
        - iot:CreateThing
      Resource:
        - "*"    

functions:
  connect-device-to-phone-request:
    handler: src/functions/connect-device-to-phone.request
    events:
      - http:
          method: get
          path: connect-device-to-phone/{deviceCode}
          cors: true
  connect-device-to-phone-process:
    handler: src/functions/connect-device-to-phone.process
    events:
      - http:
          method: post
          path: connect-device-to-phone/{deviceCode}
          cors: true    
  create-device:
    handler: src/functions/create-device.handler
    events:
      - http:
          method: post
          path: create-device
          cors: true            
resources:
  - ${file(./resources/dynamodb.yml)}