service:
  name: door-guard-api

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: functions/hello.handler
    events:
      - http:
          method: get
          path: hello
          cors: true
