Resources:
  DevicePhoneDynamoDbTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
        -
          AttributeName: deviceCode
          AttributeType: S
      KeySchema:
        -
          AttributeName: deviceCode
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: ${self:provider.environment.DYNAMODB_TABLE_DEVICE_PHONE}
  DeviceRequestTokenDynamoDbTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
        -
          AttributeName: deviceCode
          AttributeType: S
      KeySchema:
        -
          AttributeName: deviceCode
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: ${self:provider.environment.DYNAMODB_TABLE_DEVICE_REQUEST_TOKEN}    